apiVersion: operator.skywalking.apache.org/v1alpha1
kind: OAPServer
metadata:
  name: skywalking-system
  namespace: skywalking-system
spec:
  version: 8.9.1
  instances: 1
  image: ghcr.io/apache/skywalking/oap:e74adec05fd8a93ee945bcc4a3c7fcbb3761c5c7
  config:
    - name: SW_METER_ANALYZER_ACTIVE_FILES
      value: satellite
    - name: SW_TELEMETRY
      value: prometheus
    - name: SW_OTEL_RECEIVER_ENABLED_OC_RULES
      value: istio-controlplane,oap
  service:
    template:
      type: ClusterIP

---
apiVersion: operator.skywalking.apache.org/v1alpha1
kind: Satellite
metadata:
  name: skywalking-system
  namespace: skywalking-system
spec:
  version: v0.4.0
  instances: 1
  image: ghcr.io/apache/skywalking-satellite/skywalking-satellite:v1987e1d566ac90f6b58a45fd9bfa27bf8faad635
  config:
    - name: SATELLITE_TELEMETRY_EXPORT_TYPE
      value: metrics_service
  service:
    template:
      type: ClusterIP

---
apiVersion: operator.skywalking.apache.org/v1alpha1
kind: UI
metadata:
  name: skywalking-system
  namespace: skywalking-system
spec:
  version: 8.9.1
  instances: 1
  image: apache/skywalking-ui:8.9.1
  OAPServerAddress: http://skywalking-system-oap.skywalking-system:12800
  service:
    template:
      type: ClusterIP
    ingress:
      host: demo.ui.skywalking
